---

- name: "Desktop environment playbook"
  hosts: "localhost"
  roles:
    # Common roles
    - role: "locales"
      tags: "locales"
      become: true
    - role: "common"
      tags: "common"
      become: true
    - role: "dotfiles"
      tags: "dotfiles"
    - role: "devtools"
      tags: "devtools"
      become: true
    # - { role: projects-installer }
    # Server roles
    # - { role: docker, become: true }
    # Desktop roles
    - role: "regolith-desktop"
      tags: ["regolith", "regolith-desktop"]
      become: true
    - role: "slack"
      tags: ["chat"]
      become: false
    - role: "zulip"
      tags: ["chat"]
      become: false
    # User roles
    # ...
