---

- name: "Get Ubuntu codename"
  set_fact:
    UBUNTU_CODENAME: "{{ lookup('file', '/etc/os-release') | regex_search('UBUNTU_CODENAME=(.*)', '\\1') | first }}"

- name: "Configure Regolith Desktop signing key"
  get_url:
    url: "https://archive.regolith-desktop.com/regolith.key"
    dest: "/usr/share/keyrings/regolith-desktop.asc"

- name: "Configure Regolith Desktop Apt repository"
  apt_repository:
    filename: "regolith-desktop"
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/regolith-desktop.asc] https://archive.regolith-desktop.com/ubuntu/stable {{ UBUNTU_CODENAME }} v3.2"
    state: "present"

- name: "Install Regolith Desktop"
  apt:
    name: 
      - "regolith-desktop"
      - "regolith-compositor-picom-glx"
    state: "latest"
    update_cache: true

# Customizations
- name: "Install Regolith Desktop customization packages"
  apt:
    name: 
      - "rofi"
      - "regolith-look-nord"
    state: "latest"
    update_cache: true

- name: "Remove Regolith Desktop config partials redundant with custom config"
  apt:
    name:
      - "regolith-wm-base-launchers"
      - "regolith-wm-ftue"
      - "regolith-wm-navigation"
      - "regolith-wm-resize"
      - "regolith-wm-workspace-config"
      - "regolith-sway-control-center-regolith"
      - "regolith-sway-gtklock"
      - "regolith-sway-i3status-rs"
      - "regolith-sway-ilia"
      - "regolith-sway-session"
      ## Vestigial?:
      # - "regolith-i3-default-style"
      # - "regolith-i3-gaps-partial"
      # - "regolith-i3-i3xrocks"
      # - "regolith-i3-swap-focus"
    state: "absent"

- name: "Install Regolith Desktop"
  apt:
    name: 
      - "i3xrocks-temp"
      - "i3xrocks-memory"
      - "i3xrocks-disk-capacity"
      - "i3xrocks-wifi"
      - "i3xrocks-volume"
      - "i3xrocks-media-player"
    state: "latest"
    update_cache: true

- name: "Install custom config"
  file:
    src: "{{playbook_dir}}/files/regolith3-cfg"
    dest: "/home/{{ansible_user_id}}/.config/regolith3"
    owner: "{{ansible_user_id}}"
    group: "{{ansible_user_id}}"
    state: "link"
