---

- name: "Configure Regolith Desktop signing key"
  ansible.builtin.get_url:
    url: "https://regolith-desktop.org/regolith.key"
    dest: "/usr/share/keyrings/regolith-desktop.asc"

- name: "Configure Regolith Desktop Apt repository"
  ansible.builtin.apt_repository:
    filename: "regolith-desktop"
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/regolith-desktop.asc] https://regolith-desktop.org/release-3_2-ubuntu-jammy-amd64 jammy main"
    state: "present"

- name: "Install Regolith Desktop"
  ansible.builtin.apt:
    name: 
      - "regolith-desktop"
      - "regolith-session-flashback"  # X11
      # - "regolith-session-sway"       # Wayland
      - "regolith-look-nord"
      - "rofi"  # The default 'ilia' launcher is a bit too fiddly for me (https://github.com/regolith-linux/ilia/issues/26)
      # X11 bar widgets
      - "i3xrocks-temp"
      - "i3xrocks-memory"
      - "i3xrocks-disk-capacity"
      - "i3xrocks-wifi"
      - "i3xrocks-volume"
      - "i3xrocks-media-player"
      - "i3xrocks-battery"
      # Dependencies of our config; because we removed the regolith config that
      # depends on these, apt will think they are no longer required unless we
      # explicitly install them:
      - "gtklock"
      - "i3-swap-focus"
      - "i3status-rs"
      - "i3xrocks"
    state: "latest"
    update_cache: true

# TODO: Sway.
#
#   See https://github.com/regolith-linux/regolith-desktop/issues/920
#
#   * Update /etc/gdm/custom.conf.
#     * Replace WaylandEnable=False with True
#   * Install "regolith-session-sway", other needed package?
#   * Fix screen sharing issues: https://github.com/regolith-linux/regolith-desktop/issues/920
#      * Create ~/.config/environment.d/xdg.conf containing XDG_CURRENT_DESKTOP=GNOME:sway ?
#      * Update /usr/bin/regolith-session-wayland ?

- name: "Remove Regolith Desktop config partials redundant with custom config"
  ansible.builtin.apt:
    name:
      - "regolith-wm-base-launchers"
      - "regolith-wm-navigation"
      - "regolith-wm-swap-focus"
      - "regolith-wm-workspace-config"
      - "regolith-wm-resize"
      - "regolith-wm-ftue"  # first-time user experience
      - "regolith-i3-control-center-regolith"
      - "regolith-sway-control-center-regolith"
      - "regolith-i3-ilia"
      - "regolith-sway-ilia"
      - "regolith-i3-session"
      - "regolith-sway-session"
      - "regolith-sway-gtklock"
      - "regolith-i3-i3xrocks"
      - "regolith-sway-i3status-rs"
      # # NOT TESTED
      # - "regolith-i3-default-style"
      # - "regolith-i3-gaps-partial"
    state: "absent"

- name: "Find config files for symlinking"
  ansible.builtin.find:
    paths: "{{playbook_dir}}/files/regolith3-cfg"
    file_type: "any"
  register: "find"

- name: "Install custom config"
  ansible.builtin.file:
    src: "{{item.path}}"
    dest: "/home/{{ansible_user_id}}/.config/regolith3/{{item.path | basename}}"
    owner: "{{ansible_user_id}}"
    group: "{{ansible_user_id}}"
    state: "link"
  with_items: "{{find.files}}"
